#background_opacity = 0.5

[colors.primary]
foreground = "#ebdbb2"
background = "#282828"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"

[colors.selection]
text = "#282828"
background = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"
[font]


normal.family = "JetBrainsMonoNerdFontMono"
bold.family = "JetBrainsMonoNerdFontMono"
italic.family = "JetBrainsMonoNerdFontMono"
bold_italic.family = "JetBrainsMonoNerdFontMono"

size = 10


[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"

opacity = 1
[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 5
y = 5
